### ISSUE TITLE
Não consigo conectar a API ao postgres

### ISSUE THREAD

**Issue by Miguellyto** [glaucia86/nodejs-postgresql-azure#11]
Fiz todas as configurações: criei e setei as configurações do banco no arquivo .env na raiz da pasta API, criei um banco de dados, criei  a tabela products no Pg Admin usando sql que vem dentro do projeto. Mas a API não se comunica com o banco, quando executo a API na porta 3000 e vou lá no Postman e crio um novo produto fica horas tentando conectar e nada, já revisei todos os códigos, já assistir a o vedo da live 2x, o código está tudo ok. Você tem alguma ideia do que pode está acontecendo?

**Comment by glaucia86** [comment]
@Miguellyto please follow up this code sample (it's updated)

https://github.com/glaucia86/azure-sql-prisma-vue
