### ISSUE TITLE
Error no nome das tabelas.

### ISSUE THREAD

**Issue by mariaamelia** [glaucia86/nodejs-postgresql-azure#2]
No momento de criação das tabelas o nome da coluna do nome do produto está productName. 
No momento de inserir está sendo inserido como product_name.

a mesma coisa acontece na alteração

**Comment by glaucia86** [comment]
@mariaamelia tenta seguir esse tutorial aqui: [https://dev.to/azure/desenvolvendo-uma-aplicacao-crud-node-js-com-postgresql-3clk](https://dev.to/azure/desenvolvendo-uma-aplicacao-crud-node-js-com-postgresql-3clk)
