### ISSUE TITLE
Obrigado

### ISSUE THREAD

**Issue by murilooon** [glaucia86/nodejs-postgresql-azure#3]
Oi, Glaucia :smile: 

Eu precisava criar um CRUD simples para um trabalho da universidade e encontrei seu repo e artigo certinho sobre o que eu queria e precisava, foi de grande ajuda, pois fazia uns meses que não mexia com node :sweat_smile:  Então, queria te agradecer por ter disponibilizado pra galera, espero que as outras partes saiam também, pois nunca mexi com Azure.

PS: A API que criei baseado na sua é essa [aqui](https://github.com/murilooon/api-aviacao)

Obrigado!

**Comment by glaucia86** [comment]
Eu que agradeço!
